//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_chuju
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountInfo
    {
        public int id { get; set; }
        public string accountName { get; set; }
        public string userPassword { get; set; }
        public string email { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string cellphone { get; set; }
        public Nullable<int> region { get; set; }
        public Nullable<int> avatar { get; set; }
    
        public virtual accountPicture accountPicture { get; set; }
        public virtual regionList regionList { get; set; }
    }
}
