//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_chuju
{
    using System;
    using System.Collections.Generic;
    
    public partial class articleOutline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articleOutline()
        {
            this.articleContent = new HashSet<articleContent>();
            this.articleTagList = new HashSet<articleTagList>();
        }
    
        public int id { get; set; }
        public int articleClass { get; set; }
        public System.DateTime publishDate { get; set; }
        public string title { get; set; }
        public string intro { get; set; }
        public string articleSource { get; set; }
        public string pictureURL { get; set; }
    
        public virtual articleClass articleClass1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articleContent> articleContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articleTagList> articleTagList { get; set; }
    }
}
