//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_chuju
{
    using System;
    using System.Collections.Generic;
    
    public partial class articleContent
    {
        public int id { get; set; }
        public int articleID { get; set; }
        public int contentOrder { get; set; }
        public string contentType { get; set; }
        public string textContent { get; set; }
        public Nullable<int> pictureID { get; set; }
    
        public virtual articleOutline articleOutline { get; set; }
        public virtual articlePicture articlePicture { get; set; }
    }
}
