//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_chuju
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildingdb
    {
        public int 建案序號 { get; set; }
        public string 縣市 { get; set; }
        public string 地區 { get; set; }
        public string 建案名稱 { get; set; }
        public string 營造公司 { get; set; }
        public string 坪數規劃 { get; set; }
        public string 樓層規劃 { get; set; }
        public string 基地面積 { get; set; }
        public string 基地位置 { get; set; }
        public string 接待中心 { get; set; }
        public string 諮詢專線 { get; set; }
        public string 特點 { get; set; }
        public string 現況 { get; set; }
        public string picURL { get; set; }
    }
}
