//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_chuju
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildingdetail
    {
        public int 建案序號 { get; set; }
        public string 縣市 { get; set; }
        public string 地區 { get; set; }
        public string 建案名稱 { get; set; }
        public string 文宣1 { get; set; }
        public string 文宣2 { get; set; }
        public string 文宣3 { get; set; }
        public string 文宣4 { get; set; }
        public string 文宣5 { get; set; }
        public string 文宣6 { get; set; }
        public string 文宣7 { get; set; }
        public string 文宣8 { get; set; }
        public string 文宣9 { get; set; }
        public string pic1 { get; set; }
        public string pic2 { get; set; }
        public string pic3 { get; set; }
        public string pic4 { get; set; }
        public string pic5 { get; set; }
        public string pic6 { get; set; }
        public string pic7 { get; set; }
        public string pic8 { get; set; }
        public string pic9 { get; set; }
    }
}
