//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_chuju
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbchujuEntities1 : DbContext
    {
        public dbchujuEntities1()
            : base("name=dbchujuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountPicture> accountPicture { get; set; }
        public virtual DbSet<articleClass> articleClass { get; set; }
        public virtual DbSet<articleContent> articleContent { get; set; }
        public virtual DbSet<articleOutline> articleOutline { get; set; }
        public virtual DbSet<articlePicture> articlePicture { get; set; }
        public virtual DbSet<articleTagList> articleTagList { get; set; }
        public virtual DbSet<cityList> cityList { get; set; }
        public virtual DbSet<regionList> regionList { get; set; }
        public virtual DbSet<ActivityContent> ActivityContent { get; set; }
        public virtual DbSet<ActivityOutline> ActivityOutline { get; set; }
        public virtual DbSet<buildingdb> buildingdb { get; set; }
        public virtual DbSet<buildingdetail> buildingdetail { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<accountInfo> accountInfo { get; set; }
        public virtual DbSet<ClientConnection> ClientConnection { get; set; }
        public virtual DbSet<ServiceConnection> ServiceConnection { get; set; }
    }
}
